# Generated by Django 4.2 on 2024-01-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pong_points_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pong_wl_ratio',
            field=models.FloatField(default=0),
        ),
    ]
