# Generated by Django 4.2 on 2024-01-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user_pong_points_ratio_user_pong_wl_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pong_average_against',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pong_average_for',
            field=models.FloatField(default=0),
        ),
    ]
