# Generated by Django 3.2.18 on 2023-12-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
    ]
