# Generated by Django 4.2 on 2024-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_gamerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_in_game',
            field=models.BooleanField(default=False),
        ),
    ]
