# Generated by Django 4.2 on 2024-01-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_user_is_in_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brick_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='brick_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='brick_points',
            field=models.IntegerField(default=0),
        ),
    ]
