# Generated by Django 4.2 on 2024-01-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_tournament_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
