# Generated by Django 4.2 on 2024-01-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_tournament_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='nb_players',
            field=models.IntegerField(default=0),
        ),
    ]
