# Generated by Django 4.2 on 2024-01-16 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournaments', through='website.Participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
