# Generated by Django 4.2 on 2024-01-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_tournament_is_started_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='website.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='website.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='website.tournament'),
        ),
    ]
