# Generated by Django 4.2 on 2024-01-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_match_round_alter_match_participant1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_started',
        ),
    ]
