# Generated by Django 4.2 on 2024-01-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_tournament_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='quarters',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tournament',
            name='semis',
            field=models.JSONField(default=list),
        ),
    ]
