# Generated by Django 4.2 on 2024-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_tournament_final_tournament_quarters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='game_type',
            field=models.CharField(choices=[('PONG', 'Pong'), ('BRICK', 'Brick'), ('PONGTOURNAMENT', 'Pong Tournament')], max_length=14),
        ),
    ]
