# Generated by Django 4.2 on 2024-01-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_gamerecord_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
