FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
COPY ./certs/localhost+3.pem /etc/ssl/certs/
COPY ./certs/localhost+3-key.pem /etc/ssl/private/
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]