version: '3'

services:
  django:
    build: ./Docker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"

  nginx:
    build:
      context: ./Docker
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - django
