version: '3'

volumes:
  static_volume: {}
  media_volume: {}

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django.prod
    command: gunicorn transcendence.wsgi:application --bind 0.0.0.0:8001 --workers 3 --worker-class gevent
    ports:
      - "8001:8001"
    volumes:
      - static_volume:/app/productionfiles
      - media_volume:/app/media

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx.prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    volumes:
      - static_volume:/app/productionfiles
      - media_volume:/app/media
