FROM python:3.11
WORKDIR /app
COPY . /app
RUN pip install --upgrade pip
RUN pip install -r /app/Docker/requirements.txt
RUN python manage.py collectstatic --noinput
EXPOSE 8001
RUN chmod +x /app/Docker/entrypoint.sh
ENTRYPOINT ["/app/Docker/entrypoint.sh"]