FROM python:3.11
WORKDIR /app
COPY . /app
RUN pip install --upgrade pip
RUN pip install -r /app/Docker/requirements.txt
RUN python manage.py collectstatic --noinput
EXPOSE 8001
CMD ["gunicorn", "transcendence.wsgi:application", "--bind", "0.0.0.0:8001"]